packages:
  - apps/*
  - packages/*

allowBuilds:
  core-js: false
  esbuild: true
  rclone.js: false
  sharp: true
  workerd: true

minimumReleaseAgeExclude:
  - "@opennextjs/cloudflare@1.20.7"
  - posthog-js@1.435.5

patchedDependencies:
  braces@3.0.3: patches/braces@3.0.3.patch

overrides:
  source-map-js: 1.2.2
