"""Reproducible planning model. Python 3.10+, standard library only."""
from __future__ import annotations
import json, math
from pathlib import Path
from typing import Any
ROOT = Path(__file__).resolve().parent

def load() -> dict[str, Any]:
    return json.loads((ROOT / "assumptions.json").read_text(encoding="utf-8"))

def calculate(data: dict[str, Any], overrides: dict[str, float] | None = None) -> dict[str, Any]:
    p = {k: float(v["value"]) for k,v in data["inputs"].items()}
    p.update(overrides or {})
    for key in ("utilization", "refund_rate", "starter_share", "weekly_share", "monthly_share", "target_margin", "managed_payments_rate"):
        if not 0 <= p[key] <= 1: raise ValueError(f"{key} must be between zero and one")
    if p["weekly_share"] + p["monthly_share"] > 1: raise ValueError("Interval shares exceed one")
    if p["eur_ron"] <= 0 or p["credit_cost_eur"] < 0 or p["radar_screen_ron"] < 0 or p["screened_per_payment"] < 0: raise ValueError("Invalid FX or credit cost")
    intervals = {"weekly":p["weekly_share"], "monthly":p["monthly_share"], "annual":1-p["weekly_share"]-p["monthly_share"]}
    pay_freq = {"weekly":p["days_year"] / p["days_week"] / p["months_year"], "monthly":1., "annual":1/p["months_year"]}
    tier_rows=[]
    for name,t in data["tiers"].items():
        gross=sum(intervals[i]*t[f"{i}_price_eur"]*pay_freq[i] for i in intervals)
        payments=sum(intervals[i]*pay_freq[i] for i in intervals)
        credits=intervals["weekly"]*t["weekly_credits"]*pay_freq["weekly"] + (intervals["monthly"]+intervals["annual"])*t["monthly_credits"]
        revenue=gross*(1-p["refund_rate"])/(1+p["consumer_vat_rate"])
        refunds_net=gross*p["refund_rate"]/(1+p["consumer_vat_rate"])
        pct_fees=gross*(p["card_rate"]+p["billing_rate"]+p["tax_fee_rate"]+p["managed_payments_rate"])
        fixed_fees=payments*(p["payment_fixed_ron"]+p["radar_screen_ron"]*p["screened_per_payment"])/p["eur_ron"]
        fx=gross*p["fx_reserve_rate"]
        dispute=payments*p["dispute_probability"]*p["dispute_fee_eur"]
        compute=credits*p["credit_cost_eur"]*p["utilization"]
        service=p[f"{name}_service_eur"]
        variable=sum((pct_fees,fixed_fees,fx,dispute,compute,service))
        tier_rows.append(dict(tier=name,gross=gross,payments=payments,credits=credits,revenue=revenue,refunds_net=refunds_net,pct_fees=pct_fees,fixed_fees=fixed_fees,fx=fx,dispute=dispute,compute=compute,service=service,variable=variable,contribution=revenue-variable))
    keys=[k for k in tier_rows[0] if k != "tier"]
    mix={k:tier_rows[0][k]*p["starter_share"]+tier_rows[1][k]*(1-p["starter_share"]) for k in keys}
    c=mix["contribution"]; target_headroom=mix["revenue"]*(1-p["target_margin"])-mix["variable"]
    def users_needed(denom: float):
        if denom <= 0: return None
        return max(1,math.ceil(p["fixed_monthly_eur"]/denom))
    counts=[]
    for n in data["customer_counts"]:
        revenue=n*mix["revenue"]; costs=n*mix["variable"]+p["fixed_monthly_eur"]
        counts.append(dict(users=n,revenue=revenue,costs=costs,profit=revenue-costs,margin=(revenue-costs)/revenue if revenue else None))
    return dict(inputs=p,tiers=tier_rows,mix=mix,fixed=p["fixed_monthly_eur"],breakeven=users_needed(c),users_for_target=users_needed(target_headroom),ceiling_margin=c/mix["revenue"] if mix["revenue"] else None,counts=counts)

def clip_example(data):
    p={k:float(v['value']) for k,v in data['inputs'].items()}
    asr=p['clip_minutes']*p['asr_usd_minute']
    inference=(p['clip_input_tokens']*p['model_input_usd_million']+p['clip_output_tokens']*p['model_output_usd_million'])/1_000_000
    sandbox=p['clip_sandbox_seconds']*(p['sandbox_vcpus']*p['sandbox_cpu_usd_second']+p['sandbox_gib']*p['sandbox_memory_usd_second'])
    usd=asr+inference+sandbox+p['extra_provider_cost_usd']
    eur=usd*p['usd_eur']*(1+p['supplier_tax_uplift'])*(1+p['retry_buffer'])
    return dict(asr_usd=asr,inference_usd=inference,sandbox_usd=sandbox,total_usd=usd,buffered_eur=eur,quote_credits=math.ceil(eur/p['credit_cost_eur']))

def main():
    data=load(); results=[]
    for scenario in data['scenarios']:
        r=calculate(data,scenario['overrides']);r['name']=scenario['name'];results.append(r)
    payload=dict(as_of=data['as_of'],scenarios=results,clip_example=clip_example(data))
    (ROOT/'results.json').write_text(json.dumps(payload,indent=2)+'\n',encoding='utf-8')
    lines=['# Calculated planning scenarios','', 'Generated by `python finance/calculate.py`. These are estimates, not observed costs or tax settings.','', '| Scenario | Net revenue/user-month | Variable cost/user-month | Fixed/month | Break-even users | Users for 60% margin | Margin ceiling before fixed costs |','| --- | ---: | ---: | ---: | ---: | ---: | ---: |']
    for r in results:
        lines.append(f"| {r['name']} | EUR {r['mix']['revenue']:.2f} | EUR {r['mix']['variable']:.2f} | EUR {r['fixed']:.2f} | {r['breakeven'] or 'Not attainable'} | {r['users_for_target'] or 'Not attainable'} | {r['ceiling_margin']:.1%} |")
    lines += ['', '## Base mixed-interval scenario','', '| Users | Net revenue/month | Operating costs/month | Operating profit/month | Operating margin |','| ---: | ---: | ---: | ---: | ---: |']
    for row in results[0]['counts']:
        margin=f"{row['margin']:.1%}" if row['margin'] is not None else 'Not defined'
        lines.append(f"| {row['users']} | EUR {row['revenue']:.2f} | EUR {row['costs']:.2f} | EUR {row['profit']:.2f} | {margin} |")
    ex=payload['clip_example']
    lines+=['', '## Illustrative 90-second source','',f"Buffered source-understanding estimate: EUR {ex['buffered_eur']:.4f}, quoted at {ex['quote_credits']} credits under these assumptions. This excludes project matching, plan generation, and code execution. It is not a throughput or accuracy benchmark.",'', '## Accounting limits','', 'Annual cash arrives upfront but revenue is normalized monthly. Payment fees use normalized payment frequency. Refunds reduce revenue and original fees remain expensed. Metered credit ceilings already include the relevant supplier-tax and retry exposure. Do not add that exposure twice. Managed Payments cases add its 3.5 percent gross-transaction fee and retain separate Billing/payment fees. The selected advanced Radar screening quote includes unsuccessful attempts through an explicit planning multiplier; ordinary included fraud handling is not billed twice. Separate Tax-calculation fees are zero for these cases. Fixed costs are scenario inputs and must rise when actual provider tiers, accountant costs, backups, or paid support require it.']
    (ROOT/'RESULTS.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')
    for r in results: print(r['name'],r['breakeven'],r['users_for_target'],round(r['mix']['revenue'],2),round(r['mix']['variable'],2))

if __name__ == '__main__': main()
